//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toyrobot.desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("toyrobot.desktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry could not rotate robot..
        /// </summary>
        internal static string Error_CouldNot_Rotate_Robot {
            get {
                return ResourceManager.GetString("Error_CouldNot_Rotate_Robot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select the direction to Face..
        /// </summary>
        internal static string Error_Invalid_Face {
            get {
                return ResourceManager.GetString("Error_Invalid_Face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid move requested..
        /// </summary>
        internal static string Error_Invalid_Move {
            get {
                return ResourceManager.GetString("Error_Invalid_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid position requested to place the robot..
        /// </summary>
        internal static string Error_Invalid_Position {
            get {
                return ResourceManager.GetString("Error_Invalid_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid position X..
        /// </summary>
        internal static string Error_Invalid_PositionX {
            get {
                return ResourceManager.GetString("Error_Invalid_PositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid position Y..
        /// </summary>
        internal static string Error_Invalid_PositionY {
            get {
                return ResourceManager.GetString("Error_Invalid_PositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to place robot before issuing any command..
        /// </summary>
        internal static string Error_Robot_NotPlaced {
            get {
                return ResourceManager.GetString("Error_Robot_NotPlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap robot_arrow {
            get {
                object obj = ResourceManager.GetObject("robot_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
